<#
.SYNOPSIS
    The generic Project Compiler. Renders a project's canonical memory
    (PROJECT_INDEX.md + ASSET_INDEX.md) from the canonical index records.

.DESCRIPTION
    Adapter-agnostic by design: it consumes ONLY the canonical effective records
    (master_index merged with the assignment overlay). It has no knowledge of
    Claude, ChatGPT, Drive, or any other source — every adapter normalizes to the
    same record shape, and the Compiler reads that shape and nothing else.

    Real projects compile into GPT-Memory\Projects\<Name>\.
    Reserved buckets compile into their own folders, so uncertain data is never
    forced into a project:
      UNASSIGNED   -> GPT-Memory\_STAGING\        (ingested, not yet audited)
      UNCLASSIFIED -> GPT-Memory\_UNCLASSIFIED\   (audited, couldn't be assigned)

.PARAMETER Project
    Project or reserved bucket to compile. Use 'ALL' to compile every project and
    bucket found in the index.

.PARAMETER Root
    Memory root. Defaults to $env:GPT_MEMORY_ROOT or <repo>\GPT-Memory.

.EXAMPLE
    .\Compile-ProjectMemory.ps1 -Project "Vinyl Lab"

.EXAMPLE
    .\Compile-ProjectMemory.ps1 -Project ALL
#>
[CmdletBinding()]
param(
    [string]$Project = 'ALL',
    [string]$Root
)

. "$PSScriptRoot\common.ps1"
. "$PSScriptRoot\import\common-ingest.ps1"

$Root = Get-MemoryRoot -Root $Root
$records = Get-EffectiveRecords -Root $Root
if (@($records).Count -eq 0) { Write-Host "Index is empty — nothing to compile." -ForegroundColor Yellow; return }

function Get-BucketDir {
    param([string]$Name)
    switch ($Name.ToUpperInvariant()) {
        'UNASSIGNED'   { return (Join-Path $Root '_STAGING') }
        'UNCLASSIFIED' { return (Join-Path $Root '_UNCLASSIFIED') }
        default        { return (Get-ProjectDir -Root $Root -Project $Name) }
    }
}

function Compile-One {
    param([string]$Name, $Items)

    $isBucket = ($script:ReservedBuckets -contains $Name.ToUpperInvariant())
    $dir = Get-BucketDir -Name $Name
    if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

    $assets = @($Items | Where-Object { $_.type -ne 'conversation' })
    $convos = @($Items | Where-Object { $_.type -eq 'conversation' })

    $byType = $Items | Group-Object type | Sort-Object Count -Descending |
        ForEach-Object { "{0}×{1}" -f $_.Count, $_.Name }
    $lastActivity = ($Items | ForEach-Object { $_.date_added } | Sort-Object -Descending | Select-Object -First 1)

    # ---- PROJECT_INDEX.md (rollup rendered from canonical records) ----
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("# PROJECT INDEX — $Name")
    [void]$sb.AppendLine()
    if ($isBucket) {
        [void]$sb.AppendLine("> Reserved bucket. Items here are **not** assigned to a real project.")
        [void]$sb.AppendLine("> Uncertain data stays here until reviewed — never forced into a project.")
        [void]$sb.AppendLine()
    }
    [void]$sb.AppendLine("- **Items:** $(@($Items).Count)  ($($byType -join ', '))")
    [void]$sb.AppendLine("- **Assets:** $(@($assets).Count)   **Conversations:** $(@($convos).Count)")
    [void]$sb.AppendLine("- **Last activity:** $lastActivity")
    [void]$sb.AppendLine("- **Compiled:** $(Get-IsoNow) (generated — do not hand-edit)")
    [void]$sb.AppendLine()
    if (@($convos).Count) {
        [void]$sb.AppendLine("## Conversations")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("| Date | Title | Source | Status | Transcript |")
        [void]$sb.AppendLine("|------|-------|--------|--------|------------|")
        foreach ($c in ($convos | Sort-Object date_added -Descending)) {
            [void]$sb.AppendLine("| $($c.date_added) | $($c.title) | $($c.source) | $($c.status) | $($c.raw_path) |")
        }
        [void]$sb.AppendLine()
    }
    if (@($assets).Count) {
        [void]$sb.AppendLine("## Assets")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("| Date | Title | Type | Status | Path |")
        [void]$sb.AppendLine("|------|-------|------|--------|------|")
        foreach ($a in ($assets | Sort-Object date_added -Descending)) {
            [void]$sb.AppendLine("| $($a.date_added) | $($a.title) | $($a.type) | $($a.status) | $($a.raw_path) |")
        }
        [void]$sb.AppendLine()
    }
    Write-TextFile -Path (Join-Path $dir 'PROJECT_INDEX.md') -Content $sb.ToString() -Root $Root

    # ---- ASSET_INDEX.md (canonical 8-column asset table) ----
    $ai = New-Object System.Text.StringBuilder
    [void]$ai.AppendLine("# ASSET INDEX — $Name")
    [void]$ai.AppendLine()
    [void]$ai.AppendLine("> Generated by the Project Compiler from the canonical index. Do not hand-edit.")
    [void]$ai.AppendLine()
    [void]$ai.AppendLine("| Asset | Date added | What it contains | Used for | Status | Related session | Local path | Converted MD |")
    [void]$ai.AppendLine("|-------|-----------|------------------|----------|--------|-----------------|------------|--------------|")
    foreach ($a in ($assets | Sort-Object date_added -Descending)) {
        $used = if ($a.purpose) { ($a.purpose -replace '\r?\n', ' ') } else { '' }
        $rel = if ($a.related_sessions) { ($a.related_sessions -join ', ') } else { '' }
        $conv = if ($a.converted_md) { $a.converted_md } else { '' }
        [void]$ai.AppendLine("| $($a.title) | $($a.date_added) | $($a.contains) | $used | $($a.status) | $rel | $($a.raw_path) | $conv |")
    }
    Write-TextFile -Path (Join-Path $dir 'ASSET_INDEX.md') -Content $ai.ToString() -Root $Root

    Write-Host ("  {0,-16} items={1,-3} assets={2,-3} convos={3,-3} -> {4}" -f $Name, @($Items).Count, @($assets).Count, @($convos).Count, $dir)
    Write-ActionLog -Root $Root -Level 'WRITE' -Message "Compiled memory for '$Name' ($(@($Items).Count) items)"
}

Write-Host "Compiling project memory (adapter-agnostic)..." -ForegroundColor Green
$groups = $records | Group-Object project
if ($Project -ne 'ALL') {
    $groups = $groups | Where-Object { $_.Name -eq $Project }
    if (-not $groups) { Write-Host "No indexed items for '$Project'." -ForegroundColor Yellow; return }
}
foreach ($g in $groups) { Compile-One -Name $g.Name -Items $g.Group }

Write-ActionLog -Root $Root -Level 'INFO' -Message "Compile-ProjectMemory complete (scope=$Project)"
